package com.glp.backend.mybatis.generate.factor.pojo;

import java.util.ArrayList;
import java.util.List;

public class GlpCompanyBankExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table glp_company_bank
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table glp_company_bank
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table glp_company_bank
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     *  构造查询条件,glp_company_bank
     */
    public GlpCompanyBankExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *  设置排序字段,glp_company_bank
     *
     * @param orderByClause 排序字段
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *  获取排序字段,glp_company_bank
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *  设置过滤重复数据,glp_company_bank
     *
     * @param distinct 是否过滤重复数据
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *  是否过滤重复数据,glp_company_bank
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *  获取当前的查询条件实例,glp_company_bank
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * ,glp_company_bank
     *
     * @param criteria 过滤条件实例
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * ,glp_company_bank
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *  创建一个查询条件,glp_company_bank
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *  内部构建查询条件对象,glp_company_bank
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *  清除查询条件,glp_company_bank
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * 卖方银行信息
     * GeneratedCriteria
     * 数据库表：glp_company_bank
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdIsNull() {
            addCriterion("enterprise_id is null");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdIsNotNull() {
            addCriterion("enterprise_id is not null");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdEqualTo(Integer value) {
            addCriterion("enterprise_id =", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdNotEqualTo(Integer value) {
            addCriterion("enterprise_id <>", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdGreaterThan(Integer value) {
            addCriterion("enterprise_id >", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("enterprise_id >=", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdLessThan(Integer value) {
            addCriterion("enterprise_id <", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdLessThanOrEqualTo(Integer value) {
            addCriterion("enterprise_id <=", value, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdIn(List<Integer> values) {
            addCriterion("enterprise_id in", values, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdNotIn(List<Integer> values) {
            addCriterion("enterprise_id not in", values, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdBetween(Integer value1, Integer value2) {
            addCriterion("enterprise_id between", value1, value2, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andEnterpriseIdNotBetween(Integer value1, Integer value2) {
            addCriterion("enterprise_id not between", value1, value2, "enterpriseId");
            return (Criteria) this;
        }

        public Criteria andBackUsernameIsNull() {
            addCriterion("back_username is null");
            return (Criteria) this;
        }

        public Criteria andBackUsernameIsNotNull() {
            addCriterion("back_username is not null");
            return (Criteria) this;
        }

        public Criteria andBackUsernameEqualTo(String value) {
            addCriterion("back_username =", value, "backUsername");
            return (Criteria) this;
        }

        public Criteria andBackUsernameNotEqualTo(String value) {
            addCriterion("back_username <>", value, "backUsername");
            return (Criteria) this;
        }

        public Criteria andBackUsernameGreaterThan(String value) {
            addCriterion("back_username >", value, "backUsername");
            return (Criteria) this;
        }

        public Criteria andBackUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("back_username >=", value, "backUsername");
            return (Criteria) this;
        }

        public Criteria andBackUsernameLessThan(String value) {
            addCriterion("back_username <", value, "backUsername");
            return (Criteria) this;
        }

        public Criteria andBackUsernameLessThanOrEqualTo(String value) {
            addCriterion("back_username <=", value, "backUsername");
            return (Criteria) this;
        }

        public Criteria andBackUsernameLike(String value) {
            addCriterion("back_username like", value, "backUsername");
            return (Criteria) this;
        }

        public Criteria andBackUsernameNotLike(String value) {
            addCriterion("back_username not like", value, "backUsername");
            return (Criteria) this;
        }

        public Criteria andBackUsernameIn(List<String> values) {
            addCriterion("back_username in", values, "backUsername");
            return (Criteria) this;
        }

        public Criteria andBackUsernameNotIn(List<String> values) {
            addCriterion("back_username not in", values, "backUsername");
            return (Criteria) this;
        }

        public Criteria andBackUsernameBetween(String value1, String value2) {
            addCriterion("back_username between", value1, value2, "backUsername");
            return (Criteria) this;
        }

        public Criteria andBackUsernameNotBetween(String value1, String value2) {
            addCriterion("back_username not between", value1, value2, "backUsername");
            return (Criteria) this;
        }

        public Criteria andBackNumberIsNull() {
            addCriterion("back_number is null");
            return (Criteria) this;
        }

        public Criteria andBackNumberIsNotNull() {
            addCriterion("back_number is not null");
            return (Criteria) this;
        }

        public Criteria andBackNumberEqualTo(String value) {
            addCriterion("back_number =", value, "backNumber");
            return (Criteria) this;
        }

        public Criteria andBackNumberNotEqualTo(String value) {
            addCriterion("back_number <>", value, "backNumber");
            return (Criteria) this;
        }

        public Criteria andBackNumberGreaterThan(String value) {
            addCriterion("back_number >", value, "backNumber");
            return (Criteria) this;
        }

        public Criteria andBackNumberGreaterThanOrEqualTo(String value) {
            addCriterion("back_number >=", value, "backNumber");
            return (Criteria) this;
        }

        public Criteria andBackNumberLessThan(String value) {
            addCriterion("back_number <", value, "backNumber");
            return (Criteria) this;
        }

        public Criteria andBackNumberLessThanOrEqualTo(String value) {
            addCriterion("back_number <=", value, "backNumber");
            return (Criteria) this;
        }

        public Criteria andBackNumberLike(String value) {
            addCriterion("back_number like", value, "backNumber");
            return (Criteria) this;
        }

        public Criteria andBackNumberNotLike(String value) {
            addCriterion("back_number not like", value, "backNumber");
            return (Criteria) this;
        }

        public Criteria andBackNumberIn(List<String> values) {
            addCriterion("back_number in", values, "backNumber");
            return (Criteria) this;
        }

        public Criteria andBackNumberNotIn(List<String> values) {
            addCriterion("back_number not in", values, "backNumber");
            return (Criteria) this;
        }

        public Criteria andBackNumberBetween(String value1, String value2) {
            addCriterion("back_number between", value1, value2, "backNumber");
            return (Criteria) this;
        }

        public Criteria andBackNumberNotBetween(String value1, String value2) {
            addCriterion("back_number not between", value1, value2, "backNumber");
            return (Criteria) this;
        }

        public Criteria andBackNameIsNull() {
            addCriterion("back_name is null");
            return (Criteria) this;
        }

        public Criteria andBackNameIsNotNull() {
            addCriterion("back_name is not null");
            return (Criteria) this;
        }

        public Criteria andBackNameEqualTo(String value) {
            addCriterion("back_name =", value, "backName");
            return (Criteria) this;
        }

        public Criteria andBackNameNotEqualTo(String value) {
            addCriterion("back_name <>", value, "backName");
            return (Criteria) this;
        }

        public Criteria andBackNameGreaterThan(String value) {
            addCriterion("back_name >", value, "backName");
            return (Criteria) this;
        }

        public Criteria andBackNameGreaterThanOrEqualTo(String value) {
            addCriterion("back_name >=", value, "backName");
            return (Criteria) this;
        }

        public Criteria andBackNameLessThan(String value) {
            addCriterion("back_name <", value, "backName");
            return (Criteria) this;
        }

        public Criteria andBackNameLessThanOrEqualTo(String value) {
            addCriterion("back_name <=", value, "backName");
            return (Criteria) this;
        }

        public Criteria andBackNameLike(String value) {
            addCriterion("back_name like", value, "backName");
            return (Criteria) this;
        }

        public Criteria andBackNameNotLike(String value) {
            addCriterion("back_name not like", value, "backName");
            return (Criteria) this;
        }

        public Criteria andBackNameIn(List<String> values) {
            addCriterion("back_name in", values, "backName");
            return (Criteria) this;
        }

        public Criteria andBackNameNotIn(List<String> values) {
            addCriterion("back_name not in", values, "backName");
            return (Criteria) this;
        }

        public Criteria andBackNameBetween(String value1, String value2) {
            addCriterion("back_name between", value1, value2, "backName");
            return (Criteria) this;
        }

        public Criteria andBackNameNotBetween(String value1, String value2) {
            addCriterion("back_name not between", value1, value2, "backName");
            return (Criteria) this;
        }

        public Criteria andBankcodeIsNull() {
            addCriterion("bankCode is null");
            return (Criteria) this;
        }

        public Criteria andBankcodeIsNotNull() {
            addCriterion("bankCode is not null");
            return (Criteria) this;
        }

        public Criteria andBankcodeEqualTo(String value) {
            addCriterion("bankCode =", value, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeNotEqualTo(String value) {
            addCriterion("bankCode <>", value, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeGreaterThan(String value) {
            addCriterion("bankCode >", value, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeGreaterThanOrEqualTo(String value) {
            addCriterion("bankCode >=", value, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeLessThan(String value) {
            addCriterion("bankCode <", value, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeLessThanOrEqualTo(String value) {
            addCriterion("bankCode <=", value, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeLike(String value) {
            addCriterion("bankCode like", value, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeNotLike(String value) {
            addCriterion("bankCode not like", value, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeIn(List<String> values) {
            addCriterion("bankCode in", values, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeNotIn(List<String> values) {
            addCriterion("bankCode not in", values, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeBetween(String value1, String value2) {
            addCriterion("bankCode between", value1, value2, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeNotBetween(String value1, String value2) {
            addCriterion("bankCode not between", value1, value2, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBackFilialeIsNull() {
            addCriterion("back_filiale is null");
            return (Criteria) this;
        }

        public Criteria andBackFilialeIsNotNull() {
            addCriterion("back_filiale is not null");
            return (Criteria) this;
        }

        public Criteria andBackFilialeEqualTo(String value) {
            addCriterion("back_filiale =", value, "backFiliale");
            return (Criteria) this;
        }

        public Criteria andBackFilialeNotEqualTo(String value) {
            addCriterion("back_filiale <>", value, "backFiliale");
            return (Criteria) this;
        }

        public Criteria andBackFilialeGreaterThan(String value) {
            addCriterion("back_filiale >", value, "backFiliale");
            return (Criteria) this;
        }

        public Criteria andBackFilialeGreaterThanOrEqualTo(String value) {
            addCriterion("back_filiale >=", value, "backFiliale");
            return (Criteria) this;
        }

        public Criteria andBackFilialeLessThan(String value) {
            addCriterion("back_filiale <", value, "backFiliale");
            return (Criteria) this;
        }

        public Criteria andBackFilialeLessThanOrEqualTo(String value) {
            addCriterion("back_filiale <=", value, "backFiliale");
            return (Criteria) this;
        }

        public Criteria andBackFilialeLike(String value) {
            addCriterion("back_filiale like", value, "backFiliale");
            return (Criteria) this;
        }

        public Criteria andBackFilialeNotLike(String value) {
            addCriterion("back_filiale not like", value, "backFiliale");
            return (Criteria) this;
        }

        public Criteria andBackFilialeIn(List<String> values) {
            addCriterion("back_filiale in", values, "backFiliale");
            return (Criteria) this;
        }

        public Criteria andBackFilialeNotIn(List<String> values) {
            addCriterion("back_filiale not in", values, "backFiliale");
            return (Criteria) this;
        }

        public Criteria andBackFilialeBetween(String value1, String value2) {
            addCriterion("back_filiale between", value1, value2, "backFiliale");
            return (Criteria) this;
        }

        public Criteria andBackFilialeNotBetween(String value1, String value2) {
            addCriterion("back_filiale not between", value1, value2, "backFiliale");
            return (Criteria) this;
        }

        public Criteria andBranchnoIsNull() {
            addCriterion("branchNo is null");
            return (Criteria) this;
        }

        public Criteria andBranchnoIsNotNull() {
            addCriterion("branchNo is not null");
            return (Criteria) this;
        }

        public Criteria andBranchnoEqualTo(String value) {
            addCriterion("branchNo =", value, "branchno");
            return (Criteria) this;
        }

        public Criteria andBranchnoNotEqualTo(String value) {
            addCriterion("branchNo <>", value, "branchno");
            return (Criteria) this;
        }

        public Criteria andBranchnoGreaterThan(String value) {
            addCriterion("branchNo >", value, "branchno");
            return (Criteria) this;
        }

        public Criteria andBranchnoGreaterThanOrEqualTo(String value) {
            addCriterion("branchNo >=", value, "branchno");
            return (Criteria) this;
        }

        public Criteria andBranchnoLessThan(String value) {
            addCriterion("branchNo <", value, "branchno");
            return (Criteria) this;
        }

        public Criteria andBranchnoLessThanOrEqualTo(String value) {
            addCriterion("branchNo <=", value, "branchno");
            return (Criteria) this;
        }

        public Criteria andBranchnoLike(String value) {
            addCriterion("branchNo like", value, "branchno");
            return (Criteria) this;
        }

        public Criteria andBranchnoNotLike(String value) {
            addCriterion("branchNo not like", value, "branchno");
            return (Criteria) this;
        }

        public Criteria andBranchnoIn(List<String> values) {
            addCriterion("branchNo in", values, "branchno");
            return (Criteria) this;
        }

        public Criteria andBranchnoNotIn(List<String> values) {
            addCriterion("branchNo not in", values, "branchno");
            return (Criteria) this;
        }

        public Criteria andBranchnoBetween(String value1, String value2) {
            addCriterion("branchNo between", value1, value2, "branchno");
            return (Criteria) this;
        }

        public Criteria andBranchnoNotBetween(String value1, String value2) {
            addCriterion("branchNo not between", value1, value2, "branchno");
            return (Criteria) this;
        }

        public Criteria andProvnameIsNull() {
            addCriterion("provName is null");
            return (Criteria) this;
        }

        public Criteria andProvnameIsNotNull() {
            addCriterion("provName is not null");
            return (Criteria) this;
        }

        public Criteria andProvnameEqualTo(String value) {
            addCriterion("provName =", value, "provname");
            return (Criteria) this;
        }

        public Criteria andProvnameNotEqualTo(String value) {
            addCriterion("provName <>", value, "provname");
            return (Criteria) this;
        }

        public Criteria andProvnameGreaterThan(String value) {
            addCriterion("provName >", value, "provname");
            return (Criteria) this;
        }

        public Criteria andProvnameGreaterThanOrEqualTo(String value) {
            addCriterion("provName >=", value, "provname");
            return (Criteria) this;
        }

        public Criteria andProvnameLessThan(String value) {
            addCriterion("provName <", value, "provname");
            return (Criteria) this;
        }

        public Criteria andProvnameLessThanOrEqualTo(String value) {
            addCriterion("provName <=", value, "provname");
            return (Criteria) this;
        }

        public Criteria andProvnameLike(String value) {
            addCriterion("provName like", value, "provname");
            return (Criteria) this;
        }

        public Criteria andProvnameNotLike(String value) {
            addCriterion("provName not like", value, "provname");
            return (Criteria) this;
        }

        public Criteria andProvnameIn(List<String> values) {
            addCriterion("provName in", values, "provname");
            return (Criteria) this;
        }

        public Criteria andProvnameNotIn(List<String> values) {
            addCriterion("provName not in", values, "provname");
            return (Criteria) this;
        }

        public Criteria andProvnameBetween(String value1, String value2) {
            addCriterion("provName between", value1, value2, "provname");
            return (Criteria) this;
        }

        public Criteria andProvnameNotBetween(String value1, String value2) {
            addCriterion("provName not between", value1, value2, "provname");
            return (Criteria) this;
        }

        public Criteria andProvidIsNull() {
            addCriterion("provId is null");
            return (Criteria) this;
        }

        public Criteria andProvidIsNotNull() {
            addCriterion("provId is not null");
            return (Criteria) this;
        }

        public Criteria andProvidEqualTo(Integer value) {
            addCriterion("provId =", value, "provid");
            return (Criteria) this;
        }

        public Criteria andProvidNotEqualTo(Integer value) {
            addCriterion("provId <>", value, "provid");
            return (Criteria) this;
        }

        public Criteria andProvidGreaterThan(Integer value) {
            addCriterion("provId >", value, "provid");
            return (Criteria) this;
        }

        public Criteria andProvidGreaterThanOrEqualTo(Integer value) {
            addCriterion("provId >=", value, "provid");
            return (Criteria) this;
        }

        public Criteria andProvidLessThan(Integer value) {
            addCriterion("provId <", value, "provid");
            return (Criteria) this;
        }

        public Criteria andProvidLessThanOrEqualTo(Integer value) {
            addCriterion("provId <=", value, "provid");
            return (Criteria) this;
        }

        public Criteria andProvidIn(List<Integer> values) {
            addCriterion("provId in", values, "provid");
            return (Criteria) this;
        }

        public Criteria andProvidNotIn(List<Integer> values) {
            addCriterion("provId not in", values, "provid");
            return (Criteria) this;
        }

        public Criteria andProvidBetween(Integer value1, Integer value2) {
            addCriterion("provId between", value1, value2, "provid");
            return (Criteria) this;
        }

        public Criteria andProvidNotBetween(Integer value1, Integer value2) {
            addCriterion("provId not between", value1, value2, "provid");
            return (Criteria) this;
        }

        public Criteria andCitynameIsNull() {
            addCriterion("cityName is null");
            return (Criteria) this;
        }

        public Criteria andCitynameIsNotNull() {
            addCriterion("cityName is not null");
            return (Criteria) this;
        }

        public Criteria andCitynameEqualTo(String value) {
            addCriterion("cityName =", value, "cityname");
            return (Criteria) this;
        }

        public Criteria andCitynameNotEqualTo(String value) {
            addCriterion("cityName <>", value, "cityname");
            return (Criteria) this;
        }

        public Criteria andCitynameGreaterThan(String value) {
            addCriterion("cityName >", value, "cityname");
            return (Criteria) this;
        }

        public Criteria andCitynameGreaterThanOrEqualTo(String value) {
            addCriterion("cityName >=", value, "cityname");
            return (Criteria) this;
        }

        public Criteria andCitynameLessThan(String value) {
            addCriterion("cityName <", value, "cityname");
            return (Criteria) this;
        }

        public Criteria andCitynameLessThanOrEqualTo(String value) {
            addCriterion("cityName <=", value, "cityname");
            return (Criteria) this;
        }

        public Criteria andCitynameLike(String value) {
            addCriterion("cityName like", value, "cityname");
            return (Criteria) this;
        }

        public Criteria andCitynameNotLike(String value) {
            addCriterion("cityName not like", value, "cityname");
            return (Criteria) this;
        }

        public Criteria andCitynameIn(List<String> values) {
            addCriterion("cityName in", values, "cityname");
            return (Criteria) this;
        }

        public Criteria andCitynameNotIn(List<String> values) {
            addCriterion("cityName not in", values, "cityname");
            return (Criteria) this;
        }

        public Criteria andCitynameBetween(String value1, String value2) {
            addCriterion("cityName between", value1, value2, "cityname");
            return (Criteria) this;
        }

        public Criteria andCitynameNotBetween(String value1, String value2) {
            addCriterion("cityName not between", value1, value2, "cityname");
            return (Criteria) this;
        }

        public Criteria andCityidIsNull() {
            addCriterion("cityId is null");
            return (Criteria) this;
        }

        public Criteria andCityidIsNotNull() {
            addCriterion("cityId is not null");
            return (Criteria) this;
        }

        public Criteria andCityidEqualTo(Integer value) {
            addCriterion("cityId =", value, "cityid");
            return (Criteria) this;
        }

        public Criteria andCityidNotEqualTo(Integer value) {
            addCriterion("cityId <>", value, "cityid");
            return (Criteria) this;
        }

        public Criteria andCityidGreaterThan(Integer value) {
            addCriterion("cityId >", value, "cityid");
            return (Criteria) this;
        }

        public Criteria andCityidGreaterThanOrEqualTo(Integer value) {
            addCriterion("cityId >=", value, "cityid");
            return (Criteria) this;
        }

        public Criteria andCityidLessThan(Integer value) {
            addCriterion("cityId <", value, "cityid");
            return (Criteria) this;
        }

        public Criteria andCityidLessThanOrEqualTo(Integer value) {
            addCriterion("cityId <=", value, "cityid");
            return (Criteria) this;
        }

        public Criteria andCityidIn(List<Integer> values) {
            addCriterion("cityId in", values, "cityid");
            return (Criteria) this;
        }

        public Criteria andCityidNotIn(List<Integer> values) {
            addCriterion("cityId not in", values, "cityid");
            return (Criteria) this;
        }

        public Criteria andCityidBetween(Integer value1, Integer value2) {
            addCriterion("cityId between", value1, value2, "cityid");
            return (Criteria) this;
        }

        public Criteria andCityidNotBetween(Integer value1, Integer value2) {
            addCriterion("cityId not between", value1, value2, "cityid");
            return (Criteria) this;
        }

        public Criteria andInstanceNameIsNull() {
            addCriterion("instance_name is null");
            return (Criteria) this;
        }

        public Criteria andInstanceNameIsNotNull() {
            addCriterion("instance_name is not null");
            return (Criteria) this;
        }

        public Criteria andInstanceNameEqualTo(String value) {
            addCriterion("instance_name =", value, "instanceName");
            return (Criteria) this;
        }

        public Criteria andInstanceNameNotEqualTo(String value) {
            addCriterion("instance_name <>", value, "instanceName");
            return (Criteria) this;
        }

        public Criteria andInstanceNameGreaterThan(String value) {
            addCriterion("instance_name >", value, "instanceName");
            return (Criteria) this;
        }

        public Criteria andInstanceNameGreaterThanOrEqualTo(String value) {
            addCriterion("instance_name >=", value, "instanceName");
            return (Criteria) this;
        }

        public Criteria andInstanceNameLessThan(String value) {
            addCriterion("instance_name <", value, "instanceName");
            return (Criteria) this;
        }

        public Criteria andInstanceNameLessThanOrEqualTo(String value) {
            addCriterion("instance_name <=", value, "instanceName");
            return (Criteria) this;
        }

        public Criteria andInstanceNameLike(String value) {
            addCriterion("instance_name like", value, "instanceName");
            return (Criteria) this;
        }

        public Criteria andInstanceNameNotLike(String value) {
            addCriterion("instance_name not like", value, "instanceName");
            return (Criteria) this;
        }

        public Criteria andInstanceNameIn(List<String> values) {
            addCriterion("instance_name in", values, "instanceName");
            return (Criteria) this;
        }

        public Criteria andInstanceNameNotIn(List<String> values) {
            addCriterion("instance_name not in", values, "instanceName");
            return (Criteria) this;
        }

        public Criteria andInstanceNameBetween(String value1, String value2) {
            addCriterion("instance_name between", value1, value2, "instanceName");
            return (Criteria) this;
        }

        public Criteria andInstanceNameNotBetween(String value1, String value2) {
            addCriterion("instance_name not between", value1, value2, "instanceName");
            return (Criteria) this;
        }

        public Criteria andInstanceNumberIsNull() {
            addCriterion("instance_number is null");
            return (Criteria) this;
        }

        public Criteria andInstanceNumberIsNotNull() {
            addCriterion("instance_number is not null");
            return (Criteria) this;
        }

        public Criteria andInstanceNumberEqualTo(String value) {
            addCriterion("instance_number =", value, "instanceNumber");
            return (Criteria) this;
        }

        public Criteria andInstanceNumberNotEqualTo(String value) {
            addCriterion("instance_number <>", value, "instanceNumber");
            return (Criteria) this;
        }

        public Criteria andInstanceNumberGreaterThan(String value) {
            addCriterion("instance_number >", value, "instanceNumber");
            return (Criteria) this;
        }

        public Criteria andInstanceNumberGreaterThanOrEqualTo(String value) {
            addCriterion("instance_number >=", value, "instanceNumber");
            return (Criteria) this;
        }

        public Criteria andInstanceNumberLessThan(String value) {
            addCriterion("instance_number <", value, "instanceNumber");
            return (Criteria) this;
        }

        public Criteria andInstanceNumberLessThanOrEqualTo(String value) {
            addCriterion("instance_number <=", value, "instanceNumber");
            return (Criteria) this;
        }

        public Criteria andInstanceNumberLike(String value) {
            addCriterion("instance_number like", value, "instanceNumber");
            return (Criteria) this;
        }

        public Criteria andInstanceNumberNotLike(String value) {
            addCriterion("instance_number not like", value, "instanceNumber");
            return (Criteria) this;
        }

        public Criteria andInstanceNumberIn(List<String> values) {
            addCriterion("instance_number in", values, "instanceNumber");
            return (Criteria) this;
        }

        public Criteria andInstanceNumberNotIn(List<String> values) {
            addCriterion("instance_number not in", values, "instanceNumber");
            return (Criteria) this;
        }

        public Criteria andInstanceNumberBetween(String value1, String value2) {
            addCriterion("instance_number between", value1, value2, "instanceNumber");
            return (Criteria) this;
        }

        public Criteria andInstanceNumberNotBetween(String value1, String value2) {
            addCriterion("instance_number not between", value1, value2, "instanceNumber");
            return (Criteria) this;
        }

        public Criteria andInstanceBankExtensionIsNull() {
            addCriterion("instance_bank_extension is null");
            return (Criteria) this;
        }

        public Criteria andInstanceBankExtensionIsNotNull() {
            addCriterion("instance_bank_extension is not null");
            return (Criteria) this;
        }

        public Criteria andInstanceBankExtensionEqualTo(String value) {
            addCriterion("instance_bank_extension =", value, "instanceBankExtension");
            return (Criteria) this;
        }

        public Criteria andInstanceBankExtensionNotEqualTo(String value) {
            addCriterion("instance_bank_extension <>", value, "instanceBankExtension");
            return (Criteria) this;
        }

        public Criteria andInstanceBankExtensionGreaterThan(String value) {
            addCriterion("instance_bank_extension >", value, "instanceBankExtension");
            return (Criteria) this;
        }

        public Criteria andInstanceBankExtensionGreaterThanOrEqualTo(String value) {
            addCriterion("instance_bank_extension >=", value, "instanceBankExtension");
            return (Criteria) this;
        }

        public Criteria andInstanceBankExtensionLessThan(String value) {
            addCriterion("instance_bank_extension <", value, "instanceBankExtension");
            return (Criteria) this;
        }

        public Criteria andInstanceBankExtensionLessThanOrEqualTo(String value) {
            addCriterion("instance_bank_extension <=", value, "instanceBankExtension");
            return (Criteria) this;
        }

        public Criteria andInstanceBankExtensionLike(String value) {
            addCriterion("instance_bank_extension like", value, "instanceBankExtension");
            return (Criteria) this;
        }

        public Criteria andInstanceBankExtensionNotLike(String value) {
            addCriterion("instance_bank_extension not like", value, "instanceBankExtension");
            return (Criteria) this;
        }

        public Criteria andInstanceBankExtensionIn(List<String> values) {
            addCriterion("instance_bank_extension in", values, "instanceBankExtension");
            return (Criteria) this;
        }

        public Criteria andInstanceBankExtensionNotIn(List<String> values) {
            addCriterion("instance_bank_extension not in", values, "instanceBankExtension");
            return (Criteria) this;
        }

        public Criteria andInstanceBankExtensionBetween(String value1, String value2) {
            addCriterion("instance_bank_extension between", value1, value2, "instanceBankExtension");
            return (Criteria) this;
        }

        public Criteria andInstanceBankExtensionNotBetween(String value1, String value2) {
            addCriterion("instance_bank_extension not between", value1, value2, "instanceBankExtension");
            return (Criteria) this;
        }

        public Criteria andWjLoginnameIsNull() {
            addCriterion("wj_loginName is null");
            return (Criteria) this;
        }

        public Criteria andWjLoginnameIsNotNull() {
            addCriterion("wj_loginName is not null");
            return (Criteria) this;
        }

        public Criteria andWjLoginnameEqualTo(String value) {
            addCriterion("wj_loginName =", value, "wjLoginname");
            return (Criteria) this;
        }

        public Criteria andWjLoginnameNotEqualTo(String value) {
            addCriterion("wj_loginName <>", value, "wjLoginname");
            return (Criteria) this;
        }

        public Criteria andWjLoginnameGreaterThan(String value) {
            addCriterion("wj_loginName >", value, "wjLoginname");
            return (Criteria) this;
        }

        public Criteria andWjLoginnameGreaterThanOrEqualTo(String value) {
            addCriterion("wj_loginName >=", value, "wjLoginname");
            return (Criteria) this;
        }

        public Criteria andWjLoginnameLessThan(String value) {
            addCriterion("wj_loginName <", value, "wjLoginname");
            return (Criteria) this;
        }

        public Criteria andWjLoginnameLessThanOrEqualTo(String value) {
            addCriterion("wj_loginName <=", value, "wjLoginname");
            return (Criteria) this;
        }

        public Criteria andWjLoginnameLike(String value) {
            addCriterion("wj_loginName like", value, "wjLoginname");
            return (Criteria) this;
        }

        public Criteria andWjLoginnameNotLike(String value) {
            addCriterion("wj_loginName not like", value, "wjLoginname");
            return (Criteria) this;
        }

        public Criteria andWjLoginnameIn(List<String> values) {
            addCriterion("wj_loginName in", values, "wjLoginname");
            return (Criteria) this;
        }

        public Criteria andWjLoginnameNotIn(List<String> values) {
            addCriterion("wj_loginName not in", values, "wjLoginname");
            return (Criteria) this;
        }

        public Criteria andWjLoginnameBetween(String value1, String value2) {
            addCriterion("wj_loginName between", value1, value2, "wjLoginname");
            return (Criteria) this;
        }

        public Criteria andWjLoginnameNotBetween(String value1, String value2) {
            addCriterion("wj_loginName not between", value1, value2, "wjLoginname");
            return (Criteria) this;
        }

        public Criteria andWjLogintypeIsNull() {
            addCriterion("wj_loginType is null");
            return (Criteria) this;
        }

        public Criteria andWjLogintypeIsNotNull() {
            addCriterion("wj_loginType is not null");
            return (Criteria) this;
        }

        public Criteria andWjLogintypeEqualTo(String value) {
            addCriterion("wj_loginType =", value, "wjLogintype");
            return (Criteria) this;
        }

        public Criteria andWjLogintypeNotEqualTo(String value) {
            addCriterion("wj_loginType <>", value, "wjLogintype");
            return (Criteria) this;
        }

        public Criteria andWjLogintypeGreaterThan(String value) {
            addCriterion("wj_loginType >", value, "wjLogintype");
            return (Criteria) this;
        }

        public Criteria andWjLogintypeGreaterThanOrEqualTo(String value) {
            addCriterion("wj_loginType >=", value, "wjLogintype");
            return (Criteria) this;
        }

        public Criteria andWjLogintypeLessThan(String value) {
            addCriterion("wj_loginType <", value, "wjLogintype");
            return (Criteria) this;
        }

        public Criteria andWjLogintypeLessThanOrEqualTo(String value) {
            addCriterion("wj_loginType <=", value, "wjLogintype");
            return (Criteria) this;
        }

        public Criteria andWjLogintypeLike(String value) {
            addCriterion("wj_loginType like", value, "wjLogintype");
            return (Criteria) this;
        }

        public Criteria andWjLogintypeNotLike(String value) {
            addCriterion("wj_loginType not like", value, "wjLogintype");
            return (Criteria) this;
        }

        public Criteria andWjLogintypeIn(List<String> values) {
            addCriterion("wj_loginType in", values, "wjLogintype");
            return (Criteria) this;
        }

        public Criteria andWjLogintypeNotIn(List<String> values) {
            addCriterion("wj_loginType not in", values, "wjLogintype");
            return (Criteria) this;
        }

        public Criteria andWjLogintypeBetween(String value1, String value2) {
            addCriterion("wj_loginType between", value1, value2, "wjLogintype");
            return (Criteria) this;
        }

        public Criteria andWjLogintypeNotBetween(String value1, String value2) {
            addCriterion("wj_loginType not between", value1, value2, "wjLogintype");
            return (Criteria) this;
        }

        public Criteria andWjMemberIdIsNull() {
            addCriterion("wj_member_id is null");
            return (Criteria) this;
        }

        public Criteria andWjMemberIdIsNotNull() {
            addCriterion("wj_member_id is not null");
            return (Criteria) this;
        }

        public Criteria andWjMemberIdEqualTo(String value) {
            addCriterion("wj_member_id =", value, "wjMemberId");
            return (Criteria) this;
        }

        public Criteria andWjMemberIdNotEqualTo(String value) {
            addCriterion("wj_member_id <>", value, "wjMemberId");
            return (Criteria) this;
        }

        public Criteria andWjMemberIdGreaterThan(String value) {
            addCriterion("wj_member_id >", value, "wjMemberId");
            return (Criteria) this;
        }

        public Criteria andWjMemberIdGreaterThanOrEqualTo(String value) {
            addCriterion("wj_member_id >=", value, "wjMemberId");
            return (Criteria) this;
        }

        public Criteria andWjMemberIdLessThan(String value) {
            addCriterion("wj_member_id <", value, "wjMemberId");
            return (Criteria) this;
        }

        public Criteria andWjMemberIdLessThanOrEqualTo(String value) {
            addCriterion("wj_member_id <=", value, "wjMemberId");
            return (Criteria) this;
        }

        public Criteria andWjMemberIdLike(String value) {
            addCriterion("wj_member_id like", value, "wjMemberId");
            return (Criteria) this;
        }

        public Criteria andWjMemberIdNotLike(String value) {
            addCriterion("wj_member_id not like", value, "wjMemberId");
            return (Criteria) this;
        }

        public Criteria andWjMemberIdIn(List<String> values) {
            addCriterion("wj_member_id in", values, "wjMemberId");
            return (Criteria) this;
        }

        public Criteria andWjMemberIdNotIn(List<String> values) {
            addCriterion("wj_member_id not in", values, "wjMemberId");
            return (Criteria) this;
        }

        public Criteria andWjMemberIdBetween(String value1, String value2) {
            addCriterion("wj_member_id between", value1, value2, "wjMemberId");
            return (Criteria) this;
        }

        public Criteria andWjMemberIdNotBetween(String value1, String value2) {
            addCriterion("wj_member_id not between", value1, value2, "wjMemberId");
            return (Criteria) this;
        }

        public Criteria andWjAccountIdIsNull() {
            addCriterion("wj_account_id is null");
            return (Criteria) this;
        }

        public Criteria andWjAccountIdIsNotNull() {
            addCriterion("wj_account_id is not null");
            return (Criteria) this;
        }

        public Criteria andWjAccountIdEqualTo(String value) {
            addCriterion("wj_account_id =", value, "wjAccountId");
            return (Criteria) this;
        }

        public Criteria andWjAccountIdNotEqualTo(String value) {
            addCriterion("wj_account_id <>", value, "wjAccountId");
            return (Criteria) this;
        }

        public Criteria andWjAccountIdGreaterThan(String value) {
            addCriterion("wj_account_id >", value, "wjAccountId");
            return (Criteria) this;
        }

        public Criteria andWjAccountIdGreaterThanOrEqualTo(String value) {
            addCriterion("wj_account_id >=", value, "wjAccountId");
            return (Criteria) this;
        }

        public Criteria andWjAccountIdLessThan(String value) {
            addCriterion("wj_account_id <", value, "wjAccountId");
            return (Criteria) this;
        }

        public Criteria andWjAccountIdLessThanOrEqualTo(String value) {
            addCriterion("wj_account_id <=", value, "wjAccountId");
            return (Criteria) this;
        }

        public Criteria andWjAccountIdLike(String value) {
            addCriterion("wj_account_id like", value, "wjAccountId");
            return (Criteria) this;
        }

        public Criteria andWjAccountIdNotLike(String value) {
            addCriterion("wj_account_id not like", value, "wjAccountId");
            return (Criteria) this;
        }

        public Criteria andWjAccountIdIn(List<String> values) {
            addCriterion("wj_account_id in", values, "wjAccountId");
            return (Criteria) this;
        }

        public Criteria andWjAccountIdNotIn(List<String> values) {
            addCriterion("wj_account_id not in", values, "wjAccountId");
            return (Criteria) this;
        }

        public Criteria andWjAccountIdBetween(String value1, String value2) {
            addCriterion("wj_account_id between", value1, value2, "wjAccountId");
            return (Criteria) this;
        }

        public Criteria andWjAccountIdNotBetween(String value1, String value2) {
            addCriterion("wj_account_id not between", value1, value2, "wjAccountId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Integer value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Integer value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Integer value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Integer value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Integer value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Integer> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Integer> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Integer value1, Integer value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Integer value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Integer value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Integer value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Integer value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Integer value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Integer> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Integer> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Integer value1, Integer value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Boolean value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Boolean value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Boolean value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Boolean value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Boolean value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Boolean> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Boolean> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Boolean value1, Boolean value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andUseTypeIsNull() {
            addCriterion("use_type is null");
            return (Criteria) this;
        }

        public Criteria andUseTypeIsNotNull() {
            addCriterion("use_type is not null");
            return (Criteria) this;
        }

        public Criteria andUseTypeEqualTo(Boolean value) {
            addCriterion("use_type =", value, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeNotEqualTo(Boolean value) {
            addCriterion("use_type <>", value, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeGreaterThan(Boolean value) {
            addCriterion("use_type >", value, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("use_type >=", value, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeLessThan(Boolean value) {
            addCriterion("use_type <", value, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeLessThanOrEqualTo(Boolean value) {
            addCriterion("use_type <=", value, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeIn(List<Boolean> values) {
            addCriterion("use_type in", values, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeNotIn(List<Boolean> values) {
            addCriterion("use_type not in", values, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeBetween(Boolean value1, Boolean value2) {
            addCriterion("use_type between", value1, value2, "useType");
            return (Criteria) this;
        }

        public Criteria andUseTypeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("use_type not between", value1, value2, "useType");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Boolean value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Boolean value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Boolean value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Boolean value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Boolean> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Boolean> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("company_id is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("company_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(Integer value) {
            addCriterion("company_id =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(Integer value) {
            addCriterion("company_id <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(Integer value) {
            addCriterion("company_id >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("company_id >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(Integer value) {
            addCriterion("company_id <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(Integer value) {
            addCriterion("company_id <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<Integer> values) {
            addCriterion("company_id in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<Integer> values) {
            addCriterion("company_id not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(Integer value1, Integer value2) {
            addCriterion("company_id between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("company_id not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andSourceTypeIsNull() {
            addCriterion("source_type is null");
            return (Criteria) this;
        }

        public Criteria andSourceTypeIsNotNull() {
            addCriterion("source_type is not null");
            return (Criteria) this;
        }

        public Criteria andSourceTypeEqualTo(Boolean value) {
            addCriterion("source_type =", value, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeNotEqualTo(Boolean value) {
            addCriterion("source_type <>", value, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeGreaterThan(Boolean value) {
            addCriterion("source_type >", value, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("source_type >=", value, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeLessThan(Boolean value) {
            addCriterion("source_type <", value, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeLessThanOrEqualTo(Boolean value) {
            addCriterion("source_type <=", value, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeIn(List<Boolean> values) {
            addCriterion("source_type in", values, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeNotIn(List<Boolean> values) {
            addCriterion("source_type not in", values, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeBetween(Boolean value1, Boolean value2) {
            addCriterion("source_type between", value1, value2, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("source_type not between", value1, value2, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceIdIsNull() {
            addCriterion("source_id is null");
            return (Criteria) this;
        }

        public Criteria andSourceIdIsNotNull() {
            addCriterion("source_id is not null");
            return (Criteria) this;
        }

        public Criteria andSourceIdEqualTo(Integer value) {
            addCriterion("source_id =", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdNotEqualTo(Integer value) {
            addCriterion("source_id <>", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdGreaterThan(Integer value) {
            addCriterion("source_id >", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("source_id >=", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdLessThan(Integer value) {
            addCriterion("source_id <", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdLessThanOrEqualTo(Integer value) {
            addCriterion("source_id <=", value, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdIn(List<Integer> values) {
            addCriterion("source_id in", values, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdNotIn(List<Integer> values) {
            addCriterion("source_id not in", values, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdBetween(Integer value1, Integer value2) {
            addCriterion("source_id between", value1, value2, "sourceId");
            return (Criteria) this;
        }

        public Criteria andSourceIdNotBetween(Integer value1, Integer value2) {
            addCriterion("source_id not between", value1, value2, "sourceId");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIsNull() {
            addCriterion("audit_status is null");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIsNotNull() {
            addCriterion("audit_status is not null");
            return (Criteria) this;
        }

        public Criteria andAuditStatusEqualTo(Boolean value) {
            addCriterion("audit_status =", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotEqualTo(Boolean value) {
            addCriterion("audit_status <>", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusGreaterThan(Boolean value) {
            addCriterion("audit_status >", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("audit_status >=", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusLessThan(Boolean value) {
            addCriterion("audit_status <", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusLessThanOrEqualTo(Boolean value) {
            addCriterion("audit_status <=", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIn(List<Boolean> values) {
            addCriterion("audit_status in", values, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotIn(List<Boolean> values) {
            addCriterion("audit_status not in", values, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusBetween(Boolean value1, Boolean value2) {
            addCriterion("audit_status between", value1, value2, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("audit_status not between", value1, value2, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andIsSupplementIsNull() {
            addCriterion("is_supplement is null");
            return (Criteria) this;
        }

        public Criteria andIsSupplementIsNotNull() {
            addCriterion("is_supplement is not null");
            return (Criteria) this;
        }

        public Criteria andIsSupplementEqualTo(Boolean value) {
            addCriterion("is_supplement =", value, "isSupplement");
            return (Criteria) this;
        }

        public Criteria andIsSupplementNotEqualTo(Boolean value) {
            addCriterion("is_supplement <>", value, "isSupplement");
            return (Criteria) this;
        }

        public Criteria andIsSupplementGreaterThan(Boolean value) {
            addCriterion("is_supplement >", value, "isSupplement");
            return (Criteria) this;
        }

        public Criteria andIsSupplementGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_supplement >=", value, "isSupplement");
            return (Criteria) this;
        }

        public Criteria andIsSupplementLessThan(Boolean value) {
            addCriterion("is_supplement <", value, "isSupplement");
            return (Criteria) this;
        }

        public Criteria andIsSupplementLessThanOrEqualTo(Boolean value) {
            addCriterion("is_supplement <=", value, "isSupplement");
            return (Criteria) this;
        }

        public Criteria andIsSupplementIn(List<Boolean> values) {
            addCriterion("is_supplement in", values, "isSupplement");
            return (Criteria) this;
        }

        public Criteria andIsSupplementNotIn(List<Boolean> values) {
            addCriterion("is_supplement not in", values, "isSupplement");
            return (Criteria) this;
        }

        public Criteria andIsSupplementBetween(Boolean value1, Boolean value2) {
            addCriterion("is_supplement between", value1, value2, "isSupplement");
            return (Criteria) this;
        }

        public Criteria andIsSupplementNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_supplement not between", value1, value2, "isSupplement");
            return (Criteria) this;
        }

        public Criteria andManualpullwaterQueueidIsNull() {
            addCriterion("manualpullWater_queueId is null");
            return (Criteria) this;
        }

        public Criteria andManualpullwaterQueueidIsNotNull() {
            addCriterion("manualpullWater_queueId is not null");
            return (Criteria) this;
        }

        public Criteria andManualpullwaterQueueidEqualTo(Integer value) {
            addCriterion("manualpullWater_queueId =", value, "manualpullwaterQueueid");
            return (Criteria) this;
        }

        public Criteria andManualpullwaterQueueidNotEqualTo(Integer value) {
            addCriterion("manualpullWater_queueId <>", value, "manualpullwaterQueueid");
            return (Criteria) this;
        }

        public Criteria andManualpullwaterQueueidGreaterThan(Integer value) {
            addCriterion("manualpullWater_queueId >", value, "manualpullwaterQueueid");
            return (Criteria) this;
        }

        public Criteria andManualpullwaterQueueidGreaterThanOrEqualTo(Integer value) {
            addCriterion("manualpullWater_queueId >=", value, "manualpullwaterQueueid");
            return (Criteria) this;
        }

        public Criteria andManualpullwaterQueueidLessThan(Integer value) {
            addCriterion("manualpullWater_queueId <", value, "manualpullwaterQueueid");
            return (Criteria) this;
        }

        public Criteria andManualpullwaterQueueidLessThanOrEqualTo(Integer value) {
            addCriterion("manualpullWater_queueId <=", value, "manualpullwaterQueueid");
            return (Criteria) this;
        }

        public Criteria andManualpullwaterQueueidIn(List<Integer> values) {
            addCriterion("manualpullWater_queueId in", values, "manualpullwaterQueueid");
            return (Criteria) this;
        }

        public Criteria andManualpullwaterQueueidNotIn(List<Integer> values) {
            addCriterion("manualpullWater_queueId not in", values, "manualpullwaterQueueid");
            return (Criteria) this;
        }

        public Criteria andManualpullwaterQueueidBetween(Integer value1, Integer value2) {
            addCriterion("manualpullWater_queueId between", value1, value2, "manualpullwaterQueueid");
            return (Criteria) this;
        }

        public Criteria andManualpullwaterQueueidNotBetween(Integer value1, Integer value2) {
            addCriterion("manualpullWater_queueId not between", value1, value2, "manualpullwaterQueueid");
            return (Criteria) this;
        }
    }

    /**
     * 类注释
     * Criteria
     * 数据库表：glp_company_bank
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * 卖方银行信息
     * Criterion
     * 数据库表：glp_company_bank
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}