package com.glp.backend.mybatis.generate.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ruleItemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rule_item
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rule_item
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rule_item
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     *  构造查询条件,rule_item
     */
    public ruleItemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *  设置排序字段,rule_item
     *
     * @param orderByClause 排序字段
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *  获取排序字段,rule_item
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *  设置过滤重复数据,rule_item
     *
     * @param distinct 是否过滤重复数据
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *  是否过滤重复数据,rule_item
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *  获取当前的查询条件实例,rule_item
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * ,rule_item
     *
     * @param criteria 过滤条件实例
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * ,rule_item
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *  创建一个查询条件,rule_item
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *  内部构建查询条件对象,rule_item
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *  清除查询条件,rule_item
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * 风控规则Item
     * GeneratedCriteria
     * 数据库表：rule_item
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andModelIdIsNull() {
            addCriterion("model_id is null");
            return (Criteria) this;
        }

        public Criteria andModelIdIsNotNull() {
            addCriterion("model_id is not null");
            return (Criteria) this;
        }

        public Criteria andModelIdEqualTo(Integer value) {
            addCriterion("model_id =", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdNotEqualTo(Integer value) {
            addCriterion("model_id <>", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdGreaterThan(Integer value) {
            addCriterion("model_id >", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("model_id >=", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdLessThan(Integer value) {
            addCriterion("model_id <", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdLessThanOrEqualTo(Integer value) {
            addCriterion("model_id <=", value, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdIn(List<Integer> values) {
            addCriterion("model_id in", values, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdNotIn(List<Integer> values) {
            addCriterion("model_id not in", values, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdBetween(Integer value1, Integer value2) {
            addCriterion("model_id between", value1, value2, "modelId");
            return (Criteria) this;
        }

        public Criteria andModelIdNotBetween(Integer value1, Integer value2) {
            addCriterion("model_id not between", value1, value2, "modelId");
            return (Criteria) this;
        }

        public Criteria andSubModelIdIsNull() {
            addCriterion("sub_model_id is null");
            return (Criteria) this;
        }

        public Criteria andSubModelIdIsNotNull() {
            addCriterion("sub_model_id is not null");
            return (Criteria) this;
        }

        public Criteria andSubModelIdEqualTo(Integer value) {
            addCriterion("sub_model_id =", value, "subModelId");
            return (Criteria) this;
        }

        public Criteria andSubModelIdNotEqualTo(Integer value) {
            addCriterion("sub_model_id <>", value, "subModelId");
            return (Criteria) this;
        }

        public Criteria andSubModelIdGreaterThan(Integer value) {
            addCriterion("sub_model_id >", value, "subModelId");
            return (Criteria) this;
        }

        public Criteria andSubModelIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sub_model_id >=", value, "subModelId");
            return (Criteria) this;
        }

        public Criteria andSubModelIdLessThan(Integer value) {
            addCriterion("sub_model_id <", value, "subModelId");
            return (Criteria) this;
        }

        public Criteria andSubModelIdLessThanOrEqualTo(Integer value) {
            addCriterion("sub_model_id <=", value, "subModelId");
            return (Criteria) this;
        }

        public Criteria andSubModelIdIn(List<Integer> values) {
            addCriterion("sub_model_id in", values, "subModelId");
            return (Criteria) this;
        }

        public Criteria andSubModelIdNotIn(List<Integer> values) {
            addCriterion("sub_model_id not in", values, "subModelId");
            return (Criteria) this;
        }

        public Criteria andSubModelIdBetween(Integer value1, Integer value2) {
            addCriterion("sub_model_id between", value1, value2, "subModelId");
            return (Criteria) this;
        }

        public Criteria andSubModelIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sub_model_id not between", value1, value2, "subModelId");
            return (Criteria) this;
        }

        public Criteria andDimensionIdIsNull() {
            addCriterion("dimension_id is null");
            return (Criteria) this;
        }

        public Criteria andDimensionIdIsNotNull() {
            addCriterion("dimension_id is not null");
            return (Criteria) this;
        }

        public Criteria andDimensionIdEqualTo(Integer value) {
            addCriterion("dimension_id =", value, "dimensionId");
            return (Criteria) this;
        }

        public Criteria andDimensionIdNotEqualTo(Integer value) {
            addCriterion("dimension_id <>", value, "dimensionId");
            return (Criteria) this;
        }

        public Criteria andDimensionIdGreaterThan(Integer value) {
            addCriterion("dimension_id >", value, "dimensionId");
            return (Criteria) this;
        }

        public Criteria andDimensionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("dimension_id >=", value, "dimensionId");
            return (Criteria) this;
        }

        public Criteria andDimensionIdLessThan(Integer value) {
            addCriterion("dimension_id <", value, "dimensionId");
            return (Criteria) this;
        }

        public Criteria andDimensionIdLessThanOrEqualTo(Integer value) {
            addCriterion("dimension_id <=", value, "dimensionId");
            return (Criteria) this;
        }

        public Criteria andDimensionIdIn(List<Integer> values) {
            addCriterion("dimension_id in", values, "dimensionId");
            return (Criteria) this;
        }

        public Criteria andDimensionIdNotIn(List<Integer> values) {
            addCriterion("dimension_id not in", values, "dimensionId");
            return (Criteria) this;
        }

        public Criteria andDimensionIdBetween(Integer value1, Integer value2) {
            addCriterion("dimension_id between", value1, value2, "dimensionId");
            return (Criteria) this;
        }

        public Criteria andDimensionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("dimension_id not between", value1, value2, "dimensionId");
            return (Criteria) this;
        }

        public Criteria andRuleGroupIdIsNull() {
            addCriterion("rule_group_Id is null");
            return (Criteria) this;
        }

        public Criteria andRuleGroupIdIsNotNull() {
            addCriterion("rule_group_Id is not null");
            return (Criteria) this;
        }

        public Criteria andRuleGroupIdEqualTo(Integer value) {
            addCriterion("rule_group_Id =", value, "ruleGroupId");
            return (Criteria) this;
        }

        public Criteria andRuleGroupIdNotEqualTo(Integer value) {
            addCriterion("rule_group_Id <>", value, "ruleGroupId");
            return (Criteria) this;
        }

        public Criteria andRuleGroupIdGreaterThan(Integer value) {
            addCriterion("rule_group_Id >", value, "ruleGroupId");
            return (Criteria) this;
        }

        public Criteria andRuleGroupIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("rule_group_Id >=", value, "ruleGroupId");
            return (Criteria) this;
        }

        public Criteria andRuleGroupIdLessThan(Integer value) {
            addCriterion("rule_group_Id <", value, "ruleGroupId");
            return (Criteria) this;
        }

        public Criteria andRuleGroupIdLessThanOrEqualTo(Integer value) {
            addCriterion("rule_group_Id <=", value, "ruleGroupId");
            return (Criteria) this;
        }

        public Criteria andRuleGroupIdIn(List<Integer> values) {
            addCriterion("rule_group_Id in", values, "ruleGroupId");
            return (Criteria) this;
        }

        public Criteria andRuleGroupIdNotIn(List<Integer> values) {
            addCriterion("rule_group_Id not in", values, "ruleGroupId");
            return (Criteria) this;
        }

        public Criteria andRuleGroupIdBetween(Integer value1, Integer value2) {
            addCriterion("rule_group_Id between", value1, value2, "ruleGroupId");
            return (Criteria) this;
        }

        public Criteria andRuleGroupIdNotBetween(Integer value1, Integer value2) {
            addCriterion("rule_group_Id not between", value1, value2, "ruleGroupId");
            return (Criteria) this;
        }

        public Criteria andRuleCodeIsNull() {
            addCriterion("rule_code is null");
            return (Criteria) this;
        }

        public Criteria andRuleCodeIsNotNull() {
            addCriterion("rule_code is not null");
            return (Criteria) this;
        }

        public Criteria andRuleCodeEqualTo(String value) {
            addCriterion("rule_code =", value, "ruleCode");
            return (Criteria) this;
        }

        public Criteria andRuleCodeNotEqualTo(String value) {
            addCriterion("rule_code <>", value, "ruleCode");
            return (Criteria) this;
        }

        public Criteria andRuleCodeGreaterThan(String value) {
            addCriterion("rule_code >", value, "ruleCode");
            return (Criteria) this;
        }

        public Criteria andRuleCodeGreaterThanOrEqualTo(String value) {
            addCriterion("rule_code >=", value, "ruleCode");
            return (Criteria) this;
        }

        public Criteria andRuleCodeLessThan(String value) {
            addCriterion("rule_code <", value, "ruleCode");
            return (Criteria) this;
        }

        public Criteria andRuleCodeLessThanOrEqualTo(String value) {
            addCriterion("rule_code <=", value, "ruleCode");
            return (Criteria) this;
        }

        public Criteria andRuleCodeLike(String value) {
            addCriterion("rule_code like", value, "ruleCode");
            return (Criteria) this;
        }

        public Criteria andRuleCodeNotLike(String value) {
            addCriterion("rule_code not like", value, "ruleCode");
            return (Criteria) this;
        }

        public Criteria andRuleCodeIn(List<String> values) {
            addCriterion("rule_code in", values, "ruleCode");
            return (Criteria) this;
        }

        public Criteria andRuleCodeNotIn(List<String> values) {
            addCriterion("rule_code not in", values, "ruleCode");
            return (Criteria) this;
        }

        public Criteria andRuleCodeBetween(String value1, String value2) {
            addCriterion("rule_code between", value1, value2, "ruleCode");
            return (Criteria) this;
        }

        public Criteria andRuleCodeNotBetween(String value1, String value2) {
            addCriterion("rule_code not between", value1, value2, "ruleCode");
            return (Criteria) this;
        }

        public Criteria andRuleNameIsNull() {
            addCriterion("rule_name is null");
            return (Criteria) this;
        }

        public Criteria andRuleNameIsNotNull() {
            addCriterion("rule_name is not null");
            return (Criteria) this;
        }

        public Criteria andRuleNameEqualTo(String value) {
            addCriterion("rule_name =", value, "ruleName");
            return (Criteria) this;
        }

        public Criteria andRuleNameNotEqualTo(String value) {
            addCriterion("rule_name <>", value, "ruleName");
            return (Criteria) this;
        }

        public Criteria andRuleNameGreaterThan(String value) {
            addCriterion("rule_name >", value, "ruleName");
            return (Criteria) this;
        }

        public Criteria andRuleNameGreaterThanOrEqualTo(String value) {
            addCriterion("rule_name >=", value, "ruleName");
            return (Criteria) this;
        }

        public Criteria andRuleNameLessThan(String value) {
            addCriterion("rule_name <", value, "ruleName");
            return (Criteria) this;
        }

        public Criteria andRuleNameLessThanOrEqualTo(String value) {
            addCriterion("rule_name <=", value, "ruleName");
            return (Criteria) this;
        }

        public Criteria andRuleNameLike(String value) {
            addCriterion("rule_name like", value, "ruleName");
            return (Criteria) this;
        }

        public Criteria andRuleNameNotLike(String value) {
            addCriterion("rule_name not like", value, "ruleName");
            return (Criteria) this;
        }

        public Criteria andRuleNameIn(List<String> values) {
            addCriterion("rule_name in", values, "ruleName");
            return (Criteria) this;
        }

        public Criteria andRuleNameNotIn(List<String> values) {
            addCriterion("rule_name not in", values, "ruleName");
            return (Criteria) this;
        }

        public Criteria andRuleNameBetween(String value1, String value2) {
            addCriterion("rule_name between", value1, value2, "ruleName");
            return (Criteria) this;
        }

        public Criteria andRuleNameNotBetween(String value1, String value2) {
            addCriterion("rule_name not between", value1, value2, "ruleName");
            return (Criteria) this;
        }

        public Criteria andRuleContentIsNull() {
            addCriterion("rule_content is null");
            return (Criteria) this;
        }

        public Criteria andRuleContentIsNotNull() {
            addCriterion("rule_content is not null");
            return (Criteria) this;
        }

        public Criteria andRuleContentEqualTo(String value) {
            addCriterion("rule_content =", value, "ruleContent");
            return (Criteria) this;
        }

        public Criteria andRuleContentNotEqualTo(String value) {
            addCriterion("rule_content <>", value, "ruleContent");
            return (Criteria) this;
        }

        public Criteria andRuleContentGreaterThan(String value) {
            addCriterion("rule_content >", value, "ruleContent");
            return (Criteria) this;
        }

        public Criteria andRuleContentGreaterThanOrEqualTo(String value) {
            addCriterion("rule_content >=", value, "ruleContent");
            return (Criteria) this;
        }

        public Criteria andRuleContentLessThan(String value) {
            addCriterion("rule_content <", value, "ruleContent");
            return (Criteria) this;
        }

        public Criteria andRuleContentLessThanOrEqualTo(String value) {
            addCriterion("rule_content <=", value, "ruleContent");
            return (Criteria) this;
        }

        public Criteria andRuleContentLike(String value) {
            addCriterion("rule_content like", value, "ruleContent");
            return (Criteria) this;
        }

        public Criteria andRuleContentNotLike(String value) {
            addCriterion("rule_content not like", value, "ruleContent");
            return (Criteria) this;
        }

        public Criteria andRuleContentIn(List<String> values) {
            addCriterion("rule_content in", values, "ruleContent");
            return (Criteria) this;
        }

        public Criteria andRuleContentNotIn(List<String> values) {
            addCriterion("rule_content not in", values, "ruleContent");
            return (Criteria) this;
        }

        public Criteria andRuleContentBetween(String value1, String value2) {
            addCriterion("rule_content between", value1, value2, "ruleContent");
            return (Criteria) this;
        }

        public Criteria andRuleContentNotBetween(String value1, String value2) {
            addCriterion("rule_content not between", value1, value2, "ruleContent");
            return (Criteria) this;
        }

        public Criteria andRuleConditionIsNull() {
            addCriterion("rule_condition is null");
            return (Criteria) this;
        }

        public Criteria andRuleConditionIsNotNull() {
            addCriterion("rule_condition is not null");
            return (Criteria) this;
        }

        public Criteria andRuleConditionEqualTo(String value) {
            addCriterion("rule_condition =", value, "ruleCondition");
            return (Criteria) this;
        }

        public Criteria andRuleConditionNotEqualTo(String value) {
            addCriterion("rule_condition <>", value, "ruleCondition");
            return (Criteria) this;
        }

        public Criteria andRuleConditionGreaterThan(String value) {
            addCriterion("rule_condition >", value, "ruleCondition");
            return (Criteria) this;
        }

        public Criteria andRuleConditionGreaterThanOrEqualTo(String value) {
            addCriterion("rule_condition >=", value, "ruleCondition");
            return (Criteria) this;
        }

        public Criteria andRuleConditionLessThan(String value) {
            addCriterion("rule_condition <", value, "ruleCondition");
            return (Criteria) this;
        }

        public Criteria andRuleConditionLessThanOrEqualTo(String value) {
            addCriterion("rule_condition <=", value, "ruleCondition");
            return (Criteria) this;
        }

        public Criteria andRuleConditionLike(String value) {
            addCriterion("rule_condition like", value, "ruleCondition");
            return (Criteria) this;
        }

        public Criteria andRuleConditionNotLike(String value) {
            addCriterion("rule_condition not like", value, "ruleCondition");
            return (Criteria) this;
        }

        public Criteria andRuleConditionIn(List<String> values) {
            addCriterion("rule_condition in", values, "ruleCondition");
            return (Criteria) this;
        }

        public Criteria andRuleConditionNotIn(List<String> values) {
            addCriterion("rule_condition not in", values, "ruleCondition");
            return (Criteria) this;
        }

        public Criteria andRuleConditionBetween(String value1, String value2) {
            addCriterion("rule_condition between", value1, value2, "ruleCondition");
            return (Criteria) this;
        }

        public Criteria andRuleConditionNotBetween(String value1, String value2) {
            addCriterion("rule_condition not between", value1, value2, "ruleCondition");
            return (Criteria) this;
        }

        public Criteria andRuleConditionJsIsNull() {
            addCriterion("rule_condition_js is null");
            return (Criteria) this;
        }

        public Criteria andRuleConditionJsIsNotNull() {
            addCriterion("rule_condition_js is not null");
            return (Criteria) this;
        }

        public Criteria andRuleConditionJsEqualTo(String value) {
            addCriterion("rule_condition_js =", value, "ruleConditionJs");
            return (Criteria) this;
        }

        public Criteria andRuleConditionJsNotEqualTo(String value) {
            addCriterion("rule_condition_js <>", value, "ruleConditionJs");
            return (Criteria) this;
        }

        public Criteria andRuleConditionJsGreaterThan(String value) {
            addCriterion("rule_condition_js >", value, "ruleConditionJs");
            return (Criteria) this;
        }

        public Criteria andRuleConditionJsGreaterThanOrEqualTo(String value) {
            addCriterion("rule_condition_js >=", value, "ruleConditionJs");
            return (Criteria) this;
        }

        public Criteria andRuleConditionJsLessThan(String value) {
            addCriterion("rule_condition_js <", value, "ruleConditionJs");
            return (Criteria) this;
        }

        public Criteria andRuleConditionJsLessThanOrEqualTo(String value) {
            addCriterion("rule_condition_js <=", value, "ruleConditionJs");
            return (Criteria) this;
        }

        public Criteria andRuleConditionJsLike(String value) {
            addCriterion("rule_condition_js like", value, "ruleConditionJs");
            return (Criteria) this;
        }

        public Criteria andRuleConditionJsNotLike(String value) {
            addCriterion("rule_condition_js not like", value, "ruleConditionJs");
            return (Criteria) this;
        }

        public Criteria andRuleConditionJsIn(List<String> values) {
            addCriterion("rule_condition_js in", values, "ruleConditionJs");
            return (Criteria) this;
        }

        public Criteria andRuleConditionJsNotIn(List<String> values) {
            addCriterion("rule_condition_js not in", values, "ruleConditionJs");
            return (Criteria) this;
        }

        public Criteria andRuleConditionJsBetween(String value1, String value2) {
            addCriterion("rule_condition_js between", value1, value2, "ruleConditionJs");
            return (Criteria) this;
        }

        public Criteria andRuleConditionJsNotBetween(String value1, String value2) {
            addCriterion("rule_condition_js not between", value1, value2, "ruleConditionJs");
            return (Criteria) this;
        }

        public Criteria andRuleConditionNameIsNull() {
            addCriterion("rule_condition_name is null");
            return (Criteria) this;
        }

        public Criteria andRuleConditionNameIsNotNull() {
            addCriterion("rule_condition_name is not null");
            return (Criteria) this;
        }

        public Criteria andRuleConditionNameEqualTo(String value) {
            addCriterion("rule_condition_name =", value, "ruleConditionName");
            return (Criteria) this;
        }

        public Criteria andRuleConditionNameNotEqualTo(String value) {
            addCriterion("rule_condition_name <>", value, "ruleConditionName");
            return (Criteria) this;
        }

        public Criteria andRuleConditionNameGreaterThan(String value) {
            addCriterion("rule_condition_name >", value, "ruleConditionName");
            return (Criteria) this;
        }

        public Criteria andRuleConditionNameGreaterThanOrEqualTo(String value) {
            addCriterion("rule_condition_name >=", value, "ruleConditionName");
            return (Criteria) this;
        }

        public Criteria andRuleConditionNameLessThan(String value) {
            addCriterion("rule_condition_name <", value, "ruleConditionName");
            return (Criteria) this;
        }

        public Criteria andRuleConditionNameLessThanOrEqualTo(String value) {
            addCriterion("rule_condition_name <=", value, "ruleConditionName");
            return (Criteria) this;
        }

        public Criteria andRuleConditionNameLike(String value) {
            addCriterion("rule_condition_name like", value, "ruleConditionName");
            return (Criteria) this;
        }

        public Criteria andRuleConditionNameNotLike(String value) {
            addCriterion("rule_condition_name not like", value, "ruleConditionName");
            return (Criteria) this;
        }

        public Criteria andRuleConditionNameIn(List<String> values) {
            addCriterion("rule_condition_name in", values, "ruleConditionName");
            return (Criteria) this;
        }

        public Criteria andRuleConditionNameNotIn(List<String> values) {
            addCriterion("rule_condition_name not in", values, "ruleConditionName");
            return (Criteria) this;
        }

        public Criteria andRuleConditionNameBetween(String value1, String value2) {
            addCriterion("rule_condition_name between", value1, value2, "ruleConditionName");
            return (Criteria) this;
        }

        public Criteria andRuleConditionNameNotBetween(String value1, String value2) {
            addCriterion("rule_condition_name not between", value1, value2, "ruleConditionName");
            return (Criteria) this;
        }

        public Criteria andControlLevelIsNull() {
            addCriterion("control_level is null");
            return (Criteria) this;
        }

        public Criteria andControlLevelIsNotNull() {
            addCriterion("control_level is not null");
            return (Criteria) this;
        }

        public Criteria andControlLevelEqualTo(String value) {
            addCriterion("control_level =", value, "controlLevel");
            return (Criteria) this;
        }

        public Criteria andControlLevelNotEqualTo(String value) {
            addCriterion("control_level <>", value, "controlLevel");
            return (Criteria) this;
        }

        public Criteria andControlLevelGreaterThan(String value) {
            addCriterion("control_level >", value, "controlLevel");
            return (Criteria) this;
        }

        public Criteria andControlLevelGreaterThanOrEqualTo(String value) {
            addCriterion("control_level >=", value, "controlLevel");
            return (Criteria) this;
        }

        public Criteria andControlLevelLessThan(String value) {
            addCriterion("control_level <", value, "controlLevel");
            return (Criteria) this;
        }

        public Criteria andControlLevelLessThanOrEqualTo(String value) {
            addCriterion("control_level <=", value, "controlLevel");
            return (Criteria) this;
        }

        public Criteria andControlLevelLike(String value) {
            addCriterion("control_level like", value, "controlLevel");
            return (Criteria) this;
        }

        public Criteria andControlLevelNotLike(String value) {
            addCriterion("control_level not like", value, "controlLevel");
            return (Criteria) this;
        }

        public Criteria andControlLevelIn(List<String> values) {
            addCriterion("control_level in", values, "controlLevel");
            return (Criteria) this;
        }

        public Criteria andControlLevelNotIn(List<String> values) {
            addCriterion("control_level not in", values, "controlLevel");
            return (Criteria) this;
        }

        public Criteria andControlLevelBetween(String value1, String value2) {
            addCriterion("control_level between", value1, value2, "controlLevel");
            return (Criteria) this;
        }

        public Criteria andControlLevelNotBetween(String value1, String value2) {
            addCriterion("control_level not between", value1, value2, "controlLevel");
            return (Criteria) this;
        }

        public Criteria andMonitorTitleCodeIsNull() {
            addCriterion("monitor_title_code is null");
            return (Criteria) this;
        }

        public Criteria andMonitorTitleCodeIsNotNull() {
            addCriterion("monitor_title_code is not null");
            return (Criteria) this;
        }

        public Criteria andMonitorTitleCodeEqualTo(String value) {
            addCriterion("monitor_title_code =", value, "monitorTitleCode");
            return (Criteria) this;
        }

        public Criteria andMonitorTitleCodeNotEqualTo(String value) {
            addCriterion("monitor_title_code <>", value, "monitorTitleCode");
            return (Criteria) this;
        }

        public Criteria andMonitorTitleCodeGreaterThan(String value) {
            addCriterion("monitor_title_code >", value, "monitorTitleCode");
            return (Criteria) this;
        }

        public Criteria andMonitorTitleCodeGreaterThanOrEqualTo(String value) {
            addCriterion("monitor_title_code >=", value, "monitorTitleCode");
            return (Criteria) this;
        }

        public Criteria andMonitorTitleCodeLessThan(String value) {
            addCriterion("monitor_title_code <", value, "monitorTitleCode");
            return (Criteria) this;
        }

        public Criteria andMonitorTitleCodeLessThanOrEqualTo(String value) {
            addCriterion("monitor_title_code <=", value, "monitorTitleCode");
            return (Criteria) this;
        }

        public Criteria andMonitorTitleCodeLike(String value) {
            addCriterion("monitor_title_code like", value, "monitorTitleCode");
            return (Criteria) this;
        }

        public Criteria andMonitorTitleCodeNotLike(String value) {
            addCriterion("monitor_title_code not like", value, "monitorTitleCode");
            return (Criteria) this;
        }

        public Criteria andMonitorTitleCodeIn(List<String> values) {
            addCriterion("monitor_title_code in", values, "monitorTitleCode");
            return (Criteria) this;
        }

        public Criteria andMonitorTitleCodeNotIn(List<String> values) {
            addCriterion("monitor_title_code not in", values, "monitorTitleCode");
            return (Criteria) this;
        }

        public Criteria andMonitorTitleCodeBetween(String value1, String value2) {
            addCriterion("monitor_title_code between", value1, value2, "monitorTitleCode");
            return (Criteria) this;
        }

        public Criteria andMonitorTitleCodeNotBetween(String value1, String value2) {
            addCriterion("monitor_title_code not between", value1, value2, "monitorTitleCode");
            return (Criteria) this;
        }

        public Criteria andMonitorTitleIsNull() {
            addCriterion("monitor_title is null");
            return (Criteria) this;
        }

        public Criteria andMonitorTitleIsNotNull() {
            addCriterion("monitor_title is not null");
            return (Criteria) this;
        }

        public Criteria andMonitorTitleEqualTo(String value) {
            addCriterion("monitor_title =", value, "monitorTitle");
            return (Criteria) this;
        }

        public Criteria andMonitorTitleNotEqualTo(String value) {
            addCriterion("monitor_title <>", value, "monitorTitle");
            return (Criteria) this;
        }

        public Criteria andMonitorTitleGreaterThan(String value) {
            addCriterion("monitor_title >", value, "monitorTitle");
            return (Criteria) this;
        }

        public Criteria andMonitorTitleGreaterThanOrEqualTo(String value) {
            addCriterion("monitor_title >=", value, "monitorTitle");
            return (Criteria) this;
        }

        public Criteria andMonitorTitleLessThan(String value) {
            addCriterion("monitor_title <", value, "monitorTitle");
            return (Criteria) this;
        }

        public Criteria andMonitorTitleLessThanOrEqualTo(String value) {
            addCriterion("monitor_title <=", value, "monitorTitle");
            return (Criteria) this;
        }

        public Criteria andMonitorTitleLike(String value) {
            addCriterion("monitor_title like", value, "monitorTitle");
            return (Criteria) this;
        }

        public Criteria andMonitorTitleNotLike(String value) {
            addCriterion("monitor_title not like", value, "monitorTitle");
            return (Criteria) this;
        }

        public Criteria andMonitorTitleIn(List<String> values) {
            addCriterion("monitor_title in", values, "monitorTitle");
            return (Criteria) this;
        }

        public Criteria andMonitorTitleNotIn(List<String> values) {
            addCriterion("monitor_title not in", values, "monitorTitle");
            return (Criteria) this;
        }

        public Criteria andMonitorTitleBetween(String value1, String value2) {
            addCriterion("monitor_title between", value1, value2, "monitorTitle");
            return (Criteria) this;
        }

        public Criteria andMonitorTitleNotBetween(String value1, String value2) {
            addCriterion("monitor_title not between", value1, value2, "monitorTitle");
            return (Criteria) this;
        }

        public Criteria andRuleStatusIsNull() {
            addCriterion("rule_status is null");
            return (Criteria) this;
        }

        public Criteria andRuleStatusIsNotNull() {
            addCriterion("rule_status is not null");
            return (Criteria) this;
        }

        public Criteria andRuleStatusEqualTo(String value) {
            addCriterion("rule_status =", value, "ruleStatus");
            return (Criteria) this;
        }

        public Criteria andRuleStatusNotEqualTo(String value) {
            addCriterion("rule_status <>", value, "ruleStatus");
            return (Criteria) this;
        }

        public Criteria andRuleStatusGreaterThan(String value) {
            addCriterion("rule_status >", value, "ruleStatus");
            return (Criteria) this;
        }

        public Criteria andRuleStatusGreaterThanOrEqualTo(String value) {
            addCriterion("rule_status >=", value, "ruleStatus");
            return (Criteria) this;
        }

        public Criteria andRuleStatusLessThan(String value) {
            addCriterion("rule_status <", value, "ruleStatus");
            return (Criteria) this;
        }

        public Criteria andRuleStatusLessThanOrEqualTo(String value) {
            addCriterion("rule_status <=", value, "ruleStatus");
            return (Criteria) this;
        }

        public Criteria andRuleStatusLike(String value) {
            addCriterion("rule_status like", value, "ruleStatus");
            return (Criteria) this;
        }

        public Criteria andRuleStatusNotLike(String value) {
            addCriterion("rule_status not like", value, "ruleStatus");
            return (Criteria) this;
        }

        public Criteria andRuleStatusIn(List<String> values) {
            addCriterion("rule_status in", values, "ruleStatus");
            return (Criteria) this;
        }

        public Criteria andRuleStatusNotIn(List<String> values) {
            addCriterion("rule_status not in", values, "ruleStatus");
            return (Criteria) this;
        }

        public Criteria andRuleStatusBetween(String value1, String value2) {
            addCriterion("rule_status between", value1, value2, "ruleStatus");
            return (Criteria) this;
        }

        public Criteria andRuleStatusNotBetween(String value1, String value2) {
            addCriterion("rule_status not between", value1, value2, "ruleStatus");
            return (Criteria) this;
        }

        public Criteria andLockCycleIsNull() {
            addCriterion("lock_cycle is null");
            return (Criteria) this;
        }

        public Criteria andLockCycleIsNotNull() {
            addCriterion("lock_cycle is not null");
            return (Criteria) this;
        }

        public Criteria andLockCycleEqualTo(String value) {
            addCriterion("lock_cycle =", value, "lockCycle");
            return (Criteria) this;
        }

        public Criteria andLockCycleNotEqualTo(String value) {
            addCriterion("lock_cycle <>", value, "lockCycle");
            return (Criteria) this;
        }

        public Criteria andLockCycleGreaterThan(String value) {
            addCriterion("lock_cycle >", value, "lockCycle");
            return (Criteria) this;
        }

        public Criteria andLockCycleGreaterThanOrEqualTo(String value) {
            addCriterion("lock_cycle >=", value, "lockCycle");
            return (Criteria) this;
        }

        public Criteria andLockCycleLessThan(String value) {
            addCriterion("lock_cycle <", value, "lockCycle");
            return (Criteria) this;
        }

        public Criteria andLockCycleLessThanOrEqualTo(String value) {
            addCriterion("lock_cycle <=", value, "lockCycle");
            return (Criteria) this;
        }

        public Criteria andLockCycleLike(String value) {
            addCriterion("lock_cycle like", value, "lockCycle");
            return (Criteria) this;
        }

        public Criteria andLockCycleNotLike(String value) {
            addCriterion("lock_cycle not like", value, "lockCycle");
            return (Criteria) this;
        }

        public Criteria andLockCycleIn(List<String> values) {
            addCriterion("lock_cycle in", values, "lockCycle");
            return (Criteria) this;
        }

        public Criteria andLockCycleNotIn(List<String> values) {
            addCriterion("lock_cycle not in", values, "lockCycle");
            return (Criteria) this;
        }

        public Criteria andLockCycleBetween(String value1, String value2) {
            addCriterion("lock_cycle between", value1, value2, "lockCycle");
            return (Criteria) this;
        }

        public Criteria andLockCycleNotBetween(String value1, String value2) {
            addCriterion("lock_cycle not between", value1, value2, "lockCycle");
            return (Criteria) this;
        }

        public Criteria andCommentsIsNull() {
            addCriterion("comments is null");
            return (Criteria) this;
        }

        public Criteria andCommentsIsNotNull() {
            addCriterion("comments is not null");
            return (Criteria) this;
        }

        public Criteria andCommentsEqualTo(String value) {
            addCriterion("comments =", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotEqualTo(String value) {
            addCriterion("comments <>", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsGreaterThan(String value) {
            addCriterion("comments >", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsGreaterThanOrEqualTo(String value) {
            addCriterion("comments >=", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLessThan(String value) {
            addCriterion("comments <", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLessThanOrEqualTo(String value) {
            addCriterion("comments <=", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsLike(String value) {
            addCriterion("comments like", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotLike(String value) {
            addCriterion("comments not like", value, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsIn(List<String> values) {
            addCriterion("comments in", values, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotIn(List<String> values) {
            addCriterion("comments not in", values, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsBetween(String value1, String value2) {
            addCriterion("comments between", value1, value2, "comments");
            return (Criteria) this;
        }

        public Criteria andCommentsNotBetween(String value1, String value2) {
            addCriterion("comments not between", value1, value2, "comments");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("created_by is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("created_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("created_by =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("created_by <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("created_by >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("created_by >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("created_by <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("created_by <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("created_by like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("created_by not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("created_by in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("created_by not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("created_by between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("created_by not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNull() {
            addCriterion("updated_by is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNotNull() {
            addCriterion("updated_by is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByEqualTo(String value) {
            addCriterion("updated_by =", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotEqualTo(String value) {
            addCriterion("updated_by <>", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThan(String value) {
            addCriterion("updated_by >", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThanOrEqualTo(String value) {
            addCriterion("updated_by >=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThan(String value) {
            addCriterion("updated_by <", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThanOrEqualTo(String value) {
            addCriterion("updated_by <=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLike(String value) {
            addCriterion("updated_by like", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotLike(String value) {
            addCriterion("updated_by not like", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIn(List<String> values) {
            addCriterion("updated_by in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotIn(List<String> values) {
            addCriterion("updated_by not in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByBetween(String value1, String value2) {
            addCriterion("updated_by between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotBetween(String value1, String value2) {
            addCriterion("updated_by not between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andSysRuleIdIsNull() {
            addCriterion("sys_rule_id is null");
            return (Criteria) this;
        }

        public Criteria andSysRuleIdIsNotNull() {
            addCriterion("sys_rule_id is not null");
            return (Criteria) this;
        }

        public Criteria andSysRuleIdEqualTo(Integer value) {
            addCriterion("sys_rule_id =", value, "sysRuleId");
            return (Criteria) this;
        }

        public Criteria andSysRuleIdNotEqualTo(Integer value) {
            addCriterion("sys_rule_id <>", value, "sysRuleId");
            return (Criteria) this;
        }

        public Criteria andSysRuleIdGreaterThan(Integer value) {
            addCriterion("sys_rule_id >", value, "sysRuleId");
            return (Criteria) this;
        }

        public Criteria andSysRuleIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sys_rule_id >=", value, "sysRuleId");
            return (Criteria) this;
        }

        public Criteria andSysRuleIdLessThan(Integer value) {
            addCriterion("sys_rule_id <", value, "sysRuleId");
            return (Criteria) this;
        }

        public Criteria andSysRuleIdLessThanOrEqualTo(Integer value) {
            addCriterion("sys_rule_id <=", value, "sysRuleId");
            return (Criteria) this;
        }

        public Criteria andSysRuleIdIn(List<Integer> values) {
            addCriterion("sys_rule_id in", values, "sysRuleId");
            return (Criteria) this;
        }

        public Criteria andSysRuleIdNotIn(List<Integer> values) {
            addCriterion("sys_rule_id not in", values, "sysRuleId");
            return (Criteria) this;
        }

        public Criteria andSysRuleIdBetween(Integer value1, Integer value2) {
            addCriterion("sys_rule_id between", value1, value2, "sysRuleId");
            return (Criteria) this;
        }

        public Criteria andSysRuleIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sys_rule_id not between", value1, value2, "sysRuleId");
            return (Criteria) this;
        }

        public Criteria andCronTypeIsNull() {
            addCriterion("cron_type is null");
            return (Criteria) this;
        }

        public Criteria andCronTypeIsNotNull() {
            addCriterion("cron_type is not null");
            return (Criteria) this;
        }

        public Criteria andCronTypeEqualTo(String value) {
            addCriterion("cron_type =", value, "cronType");
            return (Criteria) this;
        }

        public Criteria andCronTypeNotEqualTo(String value) {
            addCriterion("cron_type <>", value, "cronType");
            return (Criteria) this;
        }

        public Criteria andCronTypeGreaterThan(String value) {
            addCriterion("cron_type >", value, "cronType");
            return (Criteria) this;
        }

        public Criteria andCronTypeGreaterThanOrEqualTo(String value) {
            addCriterion("cron_type >=", value, "cronType");
            return (Criteria) this;
        }

        public Criteria andCronTypeLessThan(String value) {
            addCriterion("cron_type <", value, "cronType");
            return (Criteria) this;
        }

        public Criteria andCronTypeLessThanOrEqualTo(String value) {
            addCriterion("cron_type <=", value, "cronType");
            return (Criteria) this;
        }

        public Criteria andCronTypeLike(String value) {
            addCriterion("cron_type like", value, "cronType");
            return (Criteria) this;
        }

        public Criteria andCronTypeNotLike(String value) {
            addCriterion("cron_type not like", value, "cronType");
            return (Criteria) this;
        }

        public Criteria andCronTypeIn(List<String> values) {
            addCriterion("cron_type in", values, "cronType");
            return (Criteria) this;
        }

        public Criteria andCronTypeNotIn(List<String> values) {
            addCriterion("cron_type not in", values, "cronType");
            return (Criteria) this;
        }

        public Criteria andCronTypeBetween(String value1, String value2) {
            addCriterion("cron_type between", value1, value2, "cronType");
            return (Criteria) this;
        }

        public Criteria andCronTypeNotBetween(String value1, String value2) {
            addCriterion("cron_type not between", value1, value2, "cronType");
            return (Criteria) this;
        }

        public Criteria andCronNameIsNull() {
            addCriterion("cron_name is null");
            return (Criteria) this;
        }

        public Criteria andCronNameIsNotNull() {
            addCriterion("cron_name is not null");
            return (Criteria) this;
        }

        public Criteria andCronNameEqualTo(String value) {
            addCriterion("cron_name =", value, "cronName");
            return (Criteria) this;
        }

        public Criteria andCronNameNotEqualTo(String value) {
            addCriterion("cron_name <>", value, "cronName");
            return (Criteria) this;
        }

        public Criteria andCronNameGreaterThan(String value) {
            addCriterion("cron_name >", value, "cronName");
            return (Criteria) this;
        }

        public Criteria andCronNameGreaterThanOrEqualTo(String value) {
            addCriterion("cron_name >=", value, "cronName");
            return (Criteria) this;
        }

        public Criteria andCronNameLessThan(String value) {
            addCriterion("cron_name <", value, "cronName");
            return (Criteria) this;
        }

        public Criteria andCronNameLessThanOrEqualTo(String value) {
            addCriterion("cron_name <=", value, "cronName");
            return (Criteria) this;
        }

        public Criteria andCronNameLike(String value) {
            addCriterion("cron_name like", value, "cronName");
            return (Criteria) this;
        }

        public Criteria andCronNameNotLike(String value) {
            addCriterion("cron_name not like", value, "cronName");
            return (Criteria) this;
        }

        public Criteria andCronNameIn(List<String> values) {
            addCriterion("cron_name in", values, "cronName");
            return (Criteria) this;
        }

        public Criteria andCronNameNotIn(List<String> values) {
            addCriterion("cron_name not in", values, "cronName");
            return (Criteria) this;
        }

        public Criteria andCronNameBetween(String value1, String value2) {
            addCriterion("cron_name between", value1, value2, "cronName");
            return (Criteria) this;
        }

        public Criteria andCronNameNotBetween(String value1, String value2) {
            addCriterion("cron_name not between", value1, value2, "cronName");
            return (Criteria) this;
        }

        public Criteria andRiskTypeIsNull() {
            addCriterion("risk_type is null");
            return (Criteria) this;
        }

        public Criteria andRiskTypeIsNotNull() {
            addCriterion("risk_type is not null");
            return (Criteria) this;
        }

        public Criteria andRiskTypeEqualTo(String value) {
            addCriterion("risk_type =", value, "riskType");
            return (Criteria) this;
        }

        public Criteria andRiskTypeNotEqualTo(String value) {
            addCriterion("risk_type <>", value, "riskType");
            return (Criteria) this;
        }

        public Criteria andRiskTypeGreaterThan(String value) {
            addCriterion("risk_type >", value, "riskType");
            return (Criteria) this;
        }

        public Criteria andRiskTypeGreaterThanOrEqualTo(String value) {
            addCriterion("risk_type >=", value, "riskType");
            return (Criteria) this;
        }

        public Criteria andRiskTypeLessThan(String value) {
            addCriterion("risk_type <", value, "riskType");
            return (Criteria) this;
        }

        public Criteria andRiskTypeLessThanOrEqualTo(String value) {
            addCriterion("risk_type <=", value, "riskType");
            return (Criteria) this;
        }

        public Criteria andRiskTypeLike(String value) {
            addCriterion("risk_type like", value, "riskType");
            return (Criteria) this;
        }

        public Criteria andRiskTypeNotLike(String value) {
            addCriterion("risk_type not like", value, "riskType");
            return (Criteria) this;
        }

        public Criteria andRiskTypeIn(List<String> values) {
            addCriterion("risk_type in", values, "riskType");
            return (Criteria) this;
        }

        public Criteria andRiskTypeNotIn(List<String> values) {
            addCriterion("risk_type not in", values, "riskType");
            return (Criteria) this;
        }

        public Criteria andRiskTypeBetween(String value1, String value2) {
            addCriterion("risk_type between", value1, value2, "riskType");
            return (Criteria) this;
        }

        public Criteria andRiskTypeNotBetween(String value1, String value2) {
            addCriterion("risk_type not between", value1, value2, "riskType");
            return (Criteria) this;
        }

        public Criteria andTimingTypeIsNull() {
            addCriterion("timing_type is null");
            return (Criteria) this;
        }

        public Criteria andTimingTypeIsNotNull() {
            addCriterion("timing_type is not null");
            return (Criteria) this;
        }

        public Criteria andTimingTypeEqualTo(String value) {
            addCriterion("timing_type =", value, "timingType");
            return (Criteria) this;
        }

        public Criteria andTimingTypeNotEqualTo(String value) {
            addCriterion("timing_type <>", value, "timingType");
            return (Criteria) this;
        }

        public Criteria andTimingTypeGreaterThan(String value) {
            addCriterion("timing_type >", value, "timingType");
            return (Criteria) this;
        }

        public Criteria andTimingTypeGreaterThanOrEqualTo(String value) {
            addCriterion("timing_type >=", value, "timingType");
            return (Criteria) this;
        }

        public Criteria andTimingTypeLessThan(String value) {
            addCriterion("timing_type <", value, "timingType");
            return (Criteria) this;
        }

        public Criteria andTimingTypeLessThanOrEqualTo(String value) {
            addCriterion("timing_type <=", value, "timingType");
            return (Criteria) this;
        }

        public Criteria andTimingTypeLike(String value) {
            addCriterion("timing_type like", value, "timingType");
            return (Criteria) this;
        }

        public Criteria andTimingTypeNotLike(String value) {
            addCriterion("timing_type not like", value, "timingType");
            return (Criteria) this;
        }

        public Criteria andTimingTypeIn(List<String> values) {
            addCriterion("timing_type in", values, "timingType");
            return (Criteria) this;
        }

        public Criteria andTimingTypeNotIn(List<String> values) {
            addCriterion("timing_type not in", values, "timingType");
            return (Criteria) this;
        }

        public Criteria andTimingTypeBetween(String value1, String value2) {
            addCriterion("timing_type between", value1, value2, "timingType");
            return (Criteria) this;
        }

        public Criteria andTimingTypeNotBetween(String value1, String value2) {
            addCriterion("timing_type not between", value1, value2, "timingType");
            return (Criteria) this;
        }

        public Criteria andRuleTypeIsNull() {
            addCriterion("rule_type is null");
            return (Criteria) this;
        }

        public Criteria andRuleTypeIsNotNull() {
            addCriterion("rule_type is not null");
            return (Criteria) this;
        }

        public Criteria andRuleTypeEqualTo(String value) {
            addCriterion("rule_type =", value, "ruleType");
            return (Criteria) this;
        }

        public Criteria andRuleTypeNotEqualTo(String value) {
            addCriterion("rule_type <>", value, "ruleType");
            return (Criteria) this;
        }

        public Criteria andRuleTypeGreaterThan(String value) {
            addCriterion("rule_type >", value, "ruleType");
            return (Criteria) this;
        }

        public Criteria andRuleTypeGreaterThanOrEqualTo(String value) {
            addCriterion("rule_type >=", value, "ruleType");
            return (Criteria) this;
        }

        public Criteria andRuleTypeLessThan(String value) {
            addCriterion("rule_type <", value, "ruleType");
            return (Criteria) this;
        }

        public Criteria andRuleTypeLessThanOrEqualTo(String value) {
            addCriterion("rule_type <=", value, "ruleType");
            return (Criteria) this;
        }

        public Criteria andRuleTypeLike(String value) {
            addCriterion("rule_type like", value, "ruleType");
            return (Criteria) this;
        }

        public Criteria andRuleTypeNotLike(String value) {
            addCriterion("rule_type not like", value, "ruleType");
            return (Criteria) this;
        }

        public Criteria andRuleTypeIn(List<String> values) {
            addCriterion("rule_type in", values, "ruleType");
            return (Criteria) this;
        }

        public Criteria andRuleTypeNotIn(List<String> values) {
            addCriterion("rule_type not in", values, "ruleType");
            return (Criteria) this;
        }

        public Criteria andRuleTypeBetween(String value1, String value2) {
            addCriterion("rule_type between", value1, value2, "ruleType");
            return (Criteria) this;
        }

        public Criteria andRuleTypeNotBetween(String value1, String value2) {
            addCriterion("rule_type not between", value1, value2, "ruleType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeIsNull() {
            addCriterion("business_type is null");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeIsNotNull() {
            addCriterion("business_type is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeEqualTo(String value) {
            addCriterion("business_type =", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeNotEqualTo(String value) {
            addCriterion("business_type <>", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeGreaterThan(String value) {
            addCriterion("business_type >", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeGreaterThanOrEqualTo(String value) {
            addCriterion("business_type >=", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeLessThan(String value) {
            addCriterion("business_type <", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeLessThanOrEqualTo(String value) {
            addCriterion("business_type <=", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeLike(String value) {
            addCriterion("business_type like", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeNotLike(String value) {
            addCriterion("business_type not like", value, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeIn(List<String> values) {
            addCriterion("business_type in", values, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeNotIn(List<String> values) {
            addCriterion("business_type not in", values, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeBetween(String value1, String value2) {
            addCriterion("business_type between", value1, value2, "businessType");
            return (Criteria) this;
        }

        public Criteria andBusinessTypeNotBetween(String value1, String value2) {
            addCriterion("business_type not between", value1, value2, "businessType");
            return (Criteria) this;
        }

        public Criteria andRiskLevelIsNull() {
            addCriterion("risk_level is null");
            return (Criteria) this;
        }

        public Criteria andRiskLevelIsNotNull() {
            addCriterion("risk_level is not null");
            return (Criteria) this;
        }

        public Criteria andRiskLevelEqualTo(Integer value) {
            addCriterion("risk_level =", value, "riskLevel");
            return (Criteria) this;
        }

        public Criteria andRiskLevelNotEqualTo(Integer value) {
            addCriterion("risk_level <>", value, "riskLevel");
            return (Criteria) this;
        }

        public Criteria andRiskLevelGreaterThan(Integer value) {
            addCriterion("risk_level >", value, "riskLevel");
            return (Criteria) this;
        }

        public Criteria andRiskLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("risk_level >=", value, "riskLevel");
            return (Criteria) this;
        }

        public Criteria andRiskLevelLessThan(Integer value) {
            addCriterion("risk_level <", value, "riskLevel");
            return (Criteria) this;
        }

        public Criteria andRiskLevelLessThanOrEqualTo(Integer value) {
            addCriterion("risk_level <=", value, "riskLevel");
            return (Criteria) this;
        }

        public Criteria andRiskLevelIn(List<Integer> values) {
            addCriterion("risk_level in", values, "riskLevel");
            return (Criteria) this;
        }

        public Criteria andRiskLevelNotIn(List<Integer> values) {
            addCriterion("risk_level not in", values, "riskLevel");
            return (Criteria) this;
        }

        public Criteria andRiskLevelBetween(Integer value1, Integer value2) {
            addCriterion("risk_level between", value1, value2, "riskLevel");
            return (Criteria) this;
        }

        public Criteria andRiskLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("risk_level not between", value1, value2, "riskLevel");
            return (Criteria) this;
        }
    }

    /**
     * 类注释
     * Criteria
     * 数据库表：rule_item
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * 风控规则Item
     * Criterion
     * 数据库表：rule_item
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}